# config/packages/security.yaml
security:
  enable_authenticator_manager: true

  password_hashers:
    Symfony\Component\Security\Core\User\InMemoryUser:
      algorithm: plaintext

  providers:
    in_memory:
      memory:
        users:
          admin:
            password: 'password'
            roles: ['ROLE_ADMIN']

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: in_memory
      form_login:
        login_path: /login
        check_path: /login
      logout:
        path: /logout
        target: /

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
