services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:80"
    environment:
      APP_ENV: dev
      DATABASE_URL: "sqlite:////var/www/var/data.db"
    volumes:
      - .:/var/www:delegated      # code source
      - var_data:/var/www/var     # var/ (db, cache, logs) en volume
    entrypoint: ["/entrypoint.sh"]

  node:
    image: node:20
    working_dir: /var/www
    volumes:
      - .:/var/www:delegated
    command: sh -c "yarn install && yarn encore dev --watch"

volumes:
  var_data:
